from time import sleep

# VERSÃO MAIS ESMERDIADA DESSE PROGRAMA
# print("10")
# sleep(1)
# print('9')
# sleep(1)
# print('8')
# sleep(1)
# print('7')
# sleep(1)
# print('6')
# sleep(1)
# print('5')
# sleep(1)
# print('4')
# sleep(1)
# print('3')
# sleep(1)
# print('2')
# sleep(1)
# print('1')
# sleep(1)
# print('\033[1;31mBOOM!')
for cont in range(10, -1, -1):
    print(cont)
    sleep(1)
print('\033[1;31m KAAAA BOOM!')
